name: Build and Verify Firmware of Mini Amplifier

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python (PlatformIO is Python-based)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Speeds up builds by caching Python and PlatformIO packages
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}

      # Step 4: Install PlatformIO CLI
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # Step 5: Build the firmware
      - name: Build firmware using PlatformIO
        working-directory: arduino-mini-amp/arduino-amp-firmware
        run: |
          pio run
